version: "4"
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3305:3306"
    volumes:
      - ./docker/mysql-order-service:/var/lib/mysql-order-service
      - ./docker/mysql-order-service/init.sql:/docker-entrypoint-initdb.d/init.sql